apiVersion: v1
kind: ConfigMap
metadata:
  name: app-lanchonete-configmap
  namespace: ns-lanchonete
data:
  tech_challenge_host: "http://localhost:8080"
  DATASOURCE_URL: "jdbc:mysql://bd-lanchonete:3306/lanchonete"
  DATASOURCE_USERNAME: "user_fiap"
  DATASOURCE_PASSWORD: "password_fiap"
  DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  JPA_DIALECT: "org.hibernate.dialect.MySQLDialect"